// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbBFyGfNfx_NWA07YS-7G_RlDcq71bSk4',
    appId: '1:1064087031521:web:c3d5bac65b0587138031a0',
    messagingSenderId: '1064087031521',
    projectId: 'movie-calendar-9137f',
    authDomain: 'movie-calendar-9137f.firebaseapp.com',
    storageBucket: 'movie-calendar-9137f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3mksYhlTF4qVnZ5augdHUJLFATvtcB0',
    appId: '1:1064087031521:android:b0a1f74e0cccb56b8031a0',
    messagingSenderId: '1064087031521',
    projectId: 'movie-calendar-9137f',
    storageBucket: 'movie-calendar-9137f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGmOr8QW234dIiQhGR2Cc_0xMHXeXZTVg',
    appId: '1:1064087031521:ios:0b88e4a627f6db088031a0',
    messagingSenderId: '1064087031521',
    projectId: 'movie-calendar-9137f',
    storageBucket: 'movie-calendar-9137f.firebasestorage.app',
    androidClientId: '1064087031521-3a3g4cp76aocm0d4gk776dv2vgifhvev.apps.googleusercontent.com',
    iosClientId: '1064087031521-p2rsrlesua4j378292enqh0h9d41jk2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGmOr8QW234dIiQhGR2Cc_0xMHXeXZTVg',
    appId: '1:1064087031521:ios:0b88e4a627f6db088031a0',
    messagingSenderId: '1064087031521',
    projectId: 'movie-calendar-9137f',
    storageBucket: 'movie-calendar-9137f.firebasestorage.app',
    androidClientId: '1064087031521-3a3g4cp76aocm0d4gk776dv2vgifhvev.apps.googleusercontent.com',
    iosClientId: '1064087031521-p2rsrlesua4j378292enqh0h9d41jk2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbBFyGfNfx_NWA07YS-7G_RlDcq71bSk4',
    appId: '1:1064087031521:web:da028b87a35561598031a0',
    messagingSenderId: '1064087031521',
    projectId: 'movie-calendar-9137f',
    authDomain: 'movie-calendar-9137f.firebaseapp.com',
    storageBucket: 'movie-calendar-9137f.firebasestorage.app',
  );
}